language: node_js
node_js:
- 4.2
before_script:
- npm install -g grunt-cli
script:
- npm test
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/8e145155fbaaf37cffea
    on_success: change
    on_failure: always
    on_start: never
  email: false
deploy:
  provider: npm
  email: support@kuzzle.io
  api_key:
    secure: HfL3k5RtcNnfsbbAOVGCfokYfPlmVUKfEGfOgnhWWTOBeZkmuVL6CJwYAfrgUiEgMiZZzyMjZNyhsdC4S/oiOHMGFKt3sqX9y5amvwaRj/Js4f/KuJxncwd0gfP3P809RQg+FxjdrktXsOL6MZ/dwOYM60DlgcFI26Tew6XwQwJTz35ZJrn115Ds3Vq1ZSditDF6mcJ8YyDwpyGOnFD85pNuLfkrKzrCw7svz6qsIugpO+3MC3qUfsy3IOIHEjr4tVFvQq0ogOVmZiuTiTfuND0Wf2JNfAZl/eoMGR7xDGbSsEApjgkOqZBSvIkwLsH0DzF5wZQVCpgxzi2989d/UdAUNg4zyznSM3XPREAdPKuZXf0N0GzSQ48DLjXbKgCEdDEAhilDr9gf9YqNXbzyMMkmUfSxmBt848LxCuqvBPRa3Y1/TbNMlidfiKIlUnao6pdBW28t4o0HZy8j9PW5izNhiTG1yf1HZX9LZmMjXnmrRH90cE7dgU5ithI+r0VutFVYX4MHLBl+2CMO4hlrClqerCGdrFd2tmG5tK1mVtorBSGiSwCjqhbTMtp4LULZeceLz7xMQ1CuRv7PIkkAJ5dYd2ei/ZC7p+qqspqkjStkQ53pwr6tA6bC+EzSGXXtoHoABOiO4RZMvmqhy0QCPMoEfGvk0LjU+WxxBFGeLrM=
  on:
    branch: master
    repo: kuzzleio/kuzzle-sdk-login-oauth-popup
